<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Accounts\OzapTalk.Accounts.Domain\OzapTalk.Accounts.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Accounts\OzapTalk.Accounts.Application\OzapTalk.Accounts.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Accounts\OzapTalk.Accounts.Infrastructure\OzapTalk.Accounts.Infrastructure.csproj" />
  </ItemGroup>
</Project>
