<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\SopaTalk.Accounts.Application\SopaTalk.Accounts.Application.csproj" />
    <ProjectReference Include="..\SopaTalk.Accounts.Domain\SopaTalk.Accounts.Domain.csproj" />
    <ProjectReference Include="..\..\..\SopaTalk.SharedKernel\SopaTalk.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\SopaTalk.SharedKernel.Persistence\SopaTalk.SharedKernel.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SopaTalk.Accounts.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
