<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SopaTalk.Channels.Application\SopaTalk.Channels.Application.csproj" />
    <ProjectReference Include="..\SopaTalk.Channels.Infrastructure\SopaTalk.Channels.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\SopaTalk.SharedKernel\SopaTalk.SharedKernel.csproj" />
  </ItemGroup>
</Project>
