<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\SopaTalk.Channels.Application\SopaTalk.Channels.Application.csproj" />
    <ProjectReference Include="..\SopaTalk.Channels.Domain\SopaTalk.Channels.Domain.csproj" />
    <ProjectReference Include="..\..\..\SopaTalk.SharedKernel\SopaTalk.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\SopaTalk.SharedKernel.Persistence\SopaTalk.SharedKernel.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
