<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="OzapTalk.Inbox.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OzapTalk.Inbox.Application\OzapTalk.Inbox.Application.csproj" />
    <ProjectReference Include="..\OzapTalk.Inbox.Domain\OzapTalk.Inbox.Domain.csproj" />
    <ProjectReference Include="..\..\..\OzapTalk.SharedKernel\OzapTalk.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\OzapTalk.SharedKernel.Persistence\OzapTalk.SharedKernel.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
