<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\OzapTalk.Crm.Application\OzapTalk.Crm.Application.csproj" />
    <ProjectReference Include="..\OzapTalk.Crm.Domain\OzapTalk.Crm.Domain.csproj" />
    <ProjectReference Include="..\..\..\OzapTalk.SharedKernel\OzapTalk.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\OzapTalk.SharedKernel.Persistence\OzapTalk.SharedKernel.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
